backend:
  name: git-gateway
  branch: main

media_folder: "imagens"
public_folder: "imagens"

collections:
  - name: "configuracoes"
    label: "Gerenciar Catálogo"
    delete: false
    editor:
      preview: false
    files:
      - name: "lista_produtos"
        label: "Lista de Facas"
        file: "data/produtos.json"
        fields:
          - label: "Facas Disponíveis"
            name: "produtos"
            widget: "list"
            summary: "{{title}}"
            fields:
              - { label: "Nome da Faca", name: "title", widget: "string" }
              - { label: "Preço", name: "price", widget: "string" }
              - { label: "Foto", name: "image", widget: "image" }
              - { label: "Link do WhatsApp", name: "link", widget: "string" }
